packages:
  - 'server'
  - 'client'
  - 'dashboard'
  - 'ui'
  - 'site'
allowBuilds:
  '@swc/core': true
  argon2: true
  esbuild: true
  svelte-preprocess: true
onlyBuiltDependencies:
  - esbuild
  - argon2
  - '@swc/core'
